# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/curso-lilypond',
                'doc_host': 'https://twistin.github.io',
                'git_url': 'https://github.com/twistin/curso-lilypond',
                'lib_path': 'curso_lilypond'},
  'syms': {'curso_lilypond.core': {'curso_lilypond.core.foo': ('core.html#foo', 'curso_lilypond/core.py')}}}